### ISSUE TITLE
After the posenode node is set in size, reopen the workflow and the posenode node will return to the default size

### ISSUE THREAD

**Issue by wencxxxxxx** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#121]
After the posenode node is set in size, reopen the workflow and the posenode node will return to the default size

**Comment by AlekPet** [comment]
Hi, Today I released an update, check it out! 🕵

**Comment by wencxxxxxx** [comment]
thanks

**Comment by wencxxxxxx** [comment]
After testing it, the problem still exists

![Image](https://github.com/user-attachments/assets/0de4f73c-3af0-4b3f-8eeb-2f61d2dc3ed2)

**Comment by wencxxxxxx** [comment]
There is a new problem.
When there are other nodes below the posenode, click on the red area and the posenode will be selected.

![Image](https://github.com/user-attachments/assets/663bc806-e7d5-4230-9dbd-819a9c9e12e3)

**Comment by AlekPet** [comment]
Fixed it! :)

**Comment by wencxxxxxx** [comment]
thanks

**Comment by microvswind** [comment]
is it possible to custom the size of canvas ?

**Comment by AlekPet** [comment]
Hello, last button on panel pose.
